name: Zippity Zip
on:
  push:
  pull_request:
jobs:
  composer-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r pack.zip ./
      - uses: actions/upload-artifact@v2
        with:
          name: pack.zip
          path: ./
