name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "TexturePackBuilder"
        git config --global user.email "admin@ethera.net"
        git config pull.rebase false
        git pull
        rm -f release.zip
        ls
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: debug.log README.md release.zip *.git*'
    - name: push changes to remote
      run: |

        git add -A
        git commit -m "new pack"
        git push --force
